stages:
  download:
    cmd: python src/download.py
    outs:
    - Files/Files
    deps:
    - params.yaml
  prepare:
    cmd: python src/prepare.py
    deps:
    - Files/Files
    outs:
    - Files/extracted_dataframes
    - Files/processing_dataframes
  process:
    cmd: python src/process.py
    deps:
    - Files/processing_dataframes
    outs:
    - Files/processed_dataframes
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - Files/extracted_dataframes
    - Files/processed_dataframes
    outs:
    - Files/outputs
